<img src="img/numpy_logo.png" width="20%">

# Introduzione a NumPy

NumPy è una libreria Python per la creazione e manipolazione di vettori, matrici, e in generale array multidimensionali (tensori). 


## Premessa: Struttura di un quaderno Jupyter (Python interattivo)

Ogni Jupyter Notebook consiste di due tipi di componenti:

  * **Celle di testo**, contenenti spiegazioni. Quella che state leggendo è una cella di testo. 
  * **Celle di codice**, contenenti codice eseguibile Python. Le celle di codice hanno uno sfondo grigio.


### Come eseguire le celle di codice

Le celle di codice vanno di norma eseguite in sequenza. (Ogni esecuzione modifica lo stato interno dell'interprete Python.)

Per eseguire una cella di codice: 

  1. Cliccare all'interno della cella di codice. 
  2. Cliccare il pulsante "Run" dalla barra degli strumenti. In alternativa, digitare CTRL + Invio. 

Per eseguire tutte le celle del quaderno, si può selezionare **Cell->Run all** dal menu di Jupyter. Notare però che alcune celle di codice potrebbero fallire in quanto potrebbero richiedere l'aggiunta di codice, come parte di un'esercizio. 

### Se osservate errori...

I motivi che più spesso danno luogo ad errori nell'esecuzione di celle di codice sono i seguenti: 

  * Non avete eseguito *tutte* le celle di codice precedenti alla cella di codice che segnala errore. 
  * Se la cella di codice è parte di un esercizio, allora: 
    *  Non avete ancora scritto il codice che implementa l'esercizio. 
    *  Avete scritto il codice, ma il codice contiene degli errori. 

## Importare il modulo NumPy

Eseguendo la cella seguente importiamo il modulo NumPy: 

In [1]:
import numpy as np 
np.__version__

'1.23.2'

Le caratteristiche chiave di NumPy sono: 

- *ndarray*: array multidimensionali efficienti con valori omogenei (stesso tipo di dato). Gli ndarray offrono vari metodi predefiniti per l'elaborazione rapida dei dati senza la scrittura di cicli espliciti (per esempio: calcolo della media). 
- *Vettorizzazione*: permette delle operazioni numeriche efficienti sugli ndarray, sfruttando ove possibile il parallelismo hardware.
- *Broadcasting*: definisce il comportamento di operazioni tra array multidimensionali di diversa forma. 
- *Input/output*: semplifica la lettura e scrittura dei dati da/a file. 

Per qualunque ulteriore approfondimento è sempre utile consultare la <a href="https://docs.scipy.org/doc/numpy/reference/">documentazione ufficiale NumPy</a> (sempre accessibile dal menu *Help* di Jupyter o scrivendo `?nome_di_funzione`).

## Creazione di array multidimensionali

Gli ***ndarray*** (*n-dimensional array*) sono array multidimensionali efficienti, la vera ragion d'essere di numpy. 

Per creare un ndarray usiamo la funzione `np.array`.

Gli ndarray unidimensionali (1D) permettono di rappresentare comodamente dei *vettori*. 

Per creare un ndarray unidimensionale, passiamo a `np.array` una lista di numeri. Ad esempio: 

In [2]:
an_array = np.array([1.6, 2.5, 3.1, 4.9])  # Crea un array unidimensionale popolandolo con dei valori predefiniti
print(an_array)
print(type(an_array))              # Il tipo di un ndarray è: 'numpy.ndarray'

[1.6 2.5 3.1 4.9]
<class 'numpy.ndarray'>


In [3]:
# Testiamo la forma dell'array appena creato: avrà una sola dimensione (rango 1) di lunghezza 4
print(an_array.shape)

(4,)


In [4]:
# Trattandosi di un array unidimensionale, per accedere gli elementi serve esattamente un indice
print(an_array[0], an_array[1], an_array[2], an_array[3]) 

1.6 2.5 3.1 4.9


Gli ndarray bidimensionali (2D) permettono di rappresentare comodamente delle *matrici*. 

Per creare un ndarray bidimensionale, passiamo a `np.array` una lista di liste, del tipo `[ [riga], [riga], ..., [riga] ]`. Ad esempio:  

In [5]:
another = np.array([[11,12,13],[21,22,23]])   # Crea un array bidimensionale
print(another)
print("La forma (shape) è 2 righe, 3 colonne: ", another.shape)  # righe e colonne                   
print("Accedo agli elementi [0,0], [0,1], e [1,0] dell'ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])


[[11 12 13]
 [21 22 23]]
La forma (shape) è 2 righe, 3 colonne:  (2, 3)
Accedo agli elementi [0,0], [0,1], e [1,0] dell'ndarray:  11 ,  12 ,  21


Gli ndarray possono essere creati in molti modi. 

Qui mostriamo la creazione di array di diverse forme inizializzati con diversi valori. NumPy offre vari metodi che ci permettono di creare array multidimensionali facilmente e rapidamente. 

In [6]:
# crea un array 2 x 2 di tutti zeri
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [7]:
# crea un array 2 x 2 con valori tutti pari a 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [8]:
# crea una matrice identità 2 x 2
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


In [9]:
# crea un array 1 x 2 di tutti 1
ex4 = np.ones((1,2))
print(ex4)
# nb è ancora un array bidimensionale doppie parentesi.

[[1. 1.]]


In [10]:
# notare che l'ndarray ex4 è bidimensionale (cioé di rango 2); è un array 1 x 2
print(ex4.shape)

# il che significa che per accedere a ciascun suo elemento servono due indici
print(ex4[0,1])

(1, 2)
1.0


In [11]:
# crea un array di numeri decimali (float) casuali compresi tra 0 ed 1
ex5 = np.random.random((2,2))
print(ex5)

[[0.79845152 0.35783969]
 [0.54966047 0.25884665]]


In [12]:
# crea un vettore di 6 elementi con interi casuali compresi tra 50 (incluso) e 101 (escluso)
ex6 = np.random.randint(low=50, high=101, size=(6,))
print(ex6)

[71 56 75 68 70 51]


In [13]:
# crea un vettore contenente una successione aritmetica 
ex7 = np.arange(5, 12)
print(ex7)

[ 5  6  7  8  9 10 11]


Notare che `np.arange` genera una sequenza che include il limite inferiore (5) ma non quello superiore (12). 

## Slicing

Lo slicing degli ndarray è simile allo slicing di liste e stringhe in Python e ci permette di estrarre sotto-regioni di un ndarray. 

In [14]:
# Array bidimensionale di forma (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Usiamo lo slicing per estrarre un sottoarray consistente delle prime 2 righe e delle colonne di indice 1 e 2. 

In [15]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


**Importante**: la modifica di uno slice **modifica** l'array da cui lo slice è stato estratto. 

In [16]:
print("Prima:", an_array[0, 1])   # ispezioniamo l'elemento in posizione (0, 1)  
a_slice[0, 0] = 1000    # a_slice[0, 0] fa riferimento allo stesso dato di an_array[0, 1]!
print("Dopo:", an_array[0, 1])

Prima: 12
Dopo: 1000


Possiamo combinare la normale indicizzazione intera con lo slicing per creare matrici di varie forme. 

In [17]:
# Crea un array bidimensionale di forma (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Usare sia l'indicizzazione intera che lo slicing genera un array di rango inferiore:

In [18]:
row_rank1 = an_array[1, :]    # sotto-regione di rango 1
print(row_rank1, row_rank1.shape)  # notare la presenza di un'unica coppia di parentesi []

[21 22 23 24] (4,)


Usare solo lo slicing genera un array di rango uguale all'originale: 

In [19]:
row_rank2 = an_array[1:2, :]  # sotto-regione di rango 2
print(row_rank2, row_rank2.shape)   # notare la doppia coppia di parentesi [[ ]]

[[21 22 23 24]] (1, 4)


In [20]:
# Si può fare lo stesso per le colonne di un array: 
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rango 1
print()
print(col_rank2, col_rank2.shape)  # Rango 2

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


A volte è utile usare un array di indici per accedere o modificare elementi specifici. 

In [21]:
# Crea un nuovo array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Array originale:')
print(an_array)

Array originale:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [22]:
# Crea un array di indici
col_indices = np.array([0, 1, 2, 0])
print('Indici di colonna scelti : ', col_indices)

#row_indices = np.arange(4)
row_indices = np.array([0, 1, 2, 3])
print('Indici di riga scelti : ', row_indices)

Indici di colonna scelti :  [0 1 2 0]
Indici di riga scelti :  [0 1 2 3]


In [23]:
# Esaminiamo le coppie (abbinate) di row_indices e col_indices. Indicano gli elementi che poi modificheremo. 
for row, col in zip(row_indices,col_indices):
    print(row, ",", col)

0 , 0
1 , 1
2 , 2
3 , 0


In [24]:
# Visualizziamo gli elementi selezionati dagli indici
print('Valori nell\'array a quegli indici: ',an_array[row_indices, col_indices])

Valori nell'array a quegli indici:  [11 22 33 41]


In [25]:
# Modifichiamo ciascuno degli elementi selezionati dagli indici
an_array[row_indices, col_indices] += 100000

print('Array modificato:')
print(an_array)

Array modificato:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


## Indicizzazione booleana (filtraggio)

Un ***filtro*** è un array di valori booleani che indicano se ciascun elemento di un altro array soddisfa o no una certa condizione. L'uso dei filtri ci permette di selezionare e/o modificare agevolmente gli elementi di un array che godono di particolari proprietà. 

In [26]:
# crea un array 3 x 2
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [27]:
# crea un filtro, ovvero un array di booleani che indicano se ciascun elemento soddisfa una certa condizione
filtro = (an_array > 15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notare che il filtro ha la stessa forma di an_array e contiene `True` per ogni elemento il cui corrispondente elemento di an_array è maggiore di 15 e `False` per quegli elementi il cui valore è al più 15. 

In [28]:
# Ora possiamo selezionare gli elementi dell'array che soddisfano il criterio: 
print(an_array[filtro])

[21 22 31 32]


In [29]:
# Per brevità, avremmo potuto usare anche la seguente sintassi, senza usare una variabile per l'array filtro. 
an_array[an_array > 15]

array([21, 22, 31, 32])

I filtri sono particolarmente utili per modificare gli elementi dell'array che soddisfano una certa condizione. Per esempio, aggiungiamo 100 a tutti i valori *pari* dell'array. 

In [30]:
an_array[an_array % 2 == 0] += 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


## Tipo di dati in un ndarray
Il tipo di dati memorizzati in un ndarray è assegnato automaticamente da Python in base ai valori forniti al momento della creazione dell'array. L'utente può comunque forzare un tipo particolare attraverso il parametro `dtype` (datatype). 

In [31]:
ex1 = np.array([11, 12]) # Il tipo di dati è assegnato automaticamente da Python
print(ex1.dtype)

int32


In [32]:
ex2 = np.array([11.0, 12.0]) # Il tipo di dati è assegnato automaticamente da Python
print(ex2.dtype)

float64


In [33]:
ex3 = np.array([11, 12], dtype=np.int64) # Il tipo di dati è specificato dall'utente
print(ex3.dtype)

int64


In [34]:
# possiamo richiedere il troncamento di valori in virgola mobile a valori interi
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print(ex4)

int64
[11 12]


In [35]:
# possiamo forzare l'uso di valori in virgola mobile dall'inizio
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print(ex5)

float64
[11. 21.]


## Operazioni matematiche sugli ndarray

In [36]:
x = np.array([[111,112],[121,122]], dtype=np.int64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


Di norma, le operazioni sono applicate *elemento per elemento*. Nel caso di operazioni binarie, questo avviene presupponendo che i due ndarray siano compatibili (abbiano la stessa *forma*). 

In [37]:
# operazioni elemento per elemento
print(x + y) # somma
print(x - y) # sottrazione
print(x * y) # moltiplicazione
print(x / y) # divisione
# funzioni applicate agli elementi della matrice/array
print(np.sqrt(x)) # radice quadrata
print(np.exp(x)) # esponenziale (e**x)

#NB occorre utilizzare le funzioni definite nel modulo numpy altrimenti quelle standard 
#di python non riconoscono l'oggetto nd.array 

[[322.1 324.1]
 [342.1 344.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]
[[23432.1 23755.2]
 [26753.1 27096.2]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[10.53565375 10.58300524]
 [11.         11.04536102]]
[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


**Nota**. Notare l'assenza di cicli `for`. Sarà NumPy a iterare sui vari elementi degli array e anzi, ove possibile, sfrutterà il parallelismo hardware per ottenere un risultato in tempi più rapidi (***vettorizzazione***). 

La combinazione di ndarray di forma diversa avviene invece attraverso il *broadcasting* (vedi sotto). 

## Broadcasting

Quando operiamo su più ndarray di forma diversa, il risultato è determinato dal cosiddetto ***broadcasting***. In sostanza, NumPy estende automaticamente gli operandi di forma più piccola "allungandoli" fino a farli diventare della forma compatibile con l'operando di forma più grande. Ad esempio: 

$$
\left[
\begin{array}{ccc}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{array}
\right]
+
\left[
\begin{array}{ccc}
1 & 0 & 2 \\
\end{array}
\right]
\quad \rightarrow \quad
\left[
\begin{array}{ccc}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{array}
\right]
+
\left[
\begin{array}{ccc}
1 & 0 & 2 \\
1 & 0 & 2 \\
1 & 0 & 2 \\
1 & 0 & 2 \\
\end{array}
\right]
$$

In [38]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# crea un ndarray 1 x 4 (array riga) con 3 valori
add_rows = np.array([[1, 0, 2]])
print(add_rows)

[[1 0 2]]


In [40]:
y = start + add_rows  # somma il vettore con ciascuna riga di 'start' grazie al broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


Esempio di broadcast lungo le colonne:
$$
\left[
\begin{array}{ccc}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{array}
\right]
+
\left[
\begin{array}{c}
0 \\
1 \\
2 \\
3 \\
\end{array}
\right]
\quad \rightarrow \quad
\left[
\begin{array}{ccc}
0 & 0 & 0 \\
1 & 1 & 1 \\
2 & 2 & 2 \\
3 & 3 & 3 \\
\end{array}
\right]
$$

In [41]:
# crea un ndarray 4 x 1 (array colonna) per fare broadcast sulle colonne
add_cols = np.array([[0, 1, 2, 3]])
add_cols = add_cols.T # trasposta

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [42]:
# somma l'array colonna con ciascuna colonna di 'start' grazie al broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


Esempio di broadcast lungo entrambe le dimensioni:
$$
\left[
\begin{array}{ccc}
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{array}
\right]
+
\left[
\begin{array}{c}
1\\
\end{array}
\right]
\quad \rightarrow \quad
\left[
\begin{array}{ccc}
1 & 1 & 1 \\
1 & 1 & 1 \\
1 & 1 & 1 \\
1 & 1 & 1 \\
\end{array}
\right]
$$

In [43]:
# se sommiamo una matrice 1 x 1, il broadcast avverrà lungo entrambe le dimensioni dell'array start: 
add_scalar = np.array([[1]])  
print(start + add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
# Avremmo anche potuto sommare direttamente il valore scalare a start: 
print(start + 1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Allo stesso modo possiamo moltiplicare tutti gli elementi di un ndarray per una costante.

In [45]:
print((start + 1) * 3)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


Ove necessario, possiamo riorganizzare la forma di un ndarray con il metodo `reshape`. Il metodo restituisce un nuovo ndarray in cui i contenuti sono gli stessi dell'originale, ma riorganizzati secondo la nuova forma. 

In [46]:
arr = np.arange(20)
print(arr)
new_arr = arr.reshape(4,5)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Prodotti scalari tra vettori, prodotto tra matrici, prodotto matrice-vettore

Usiamo la funzione `np.dot(x, y)` per il prodotto scalare tra due vettori (array 1D) `x` e `y`. Il risultato è uno scalare.

In [47]:
# calcoliamo il PRODOTTO SCALARE tra due vettori
x = np.array([9 , 9 ])
y = np.array([10, 10])

print(np.dot(x, y)) # si può scrivere anche x.dot(y)

180


Usiamo `A @ B` per il prodotto tra due matrici (array 2D) `A` e `B`. Il risultato è una matrice. Calcoliamo ad esempio:

$$
\left[ \begin{array}{cc} 1 & 2 \\ 0 & 1 \\ \end{array} \right] \cdot 
\left[ \begin{array}{cc} 0 & 1 \\ 1 & 0 \\ \end{array} \right]
$$

In [48]:
# calcoliamo il prodotto tra due matrici (PRODOTTO RIGHE PER COLONNE)
A = np.array([[1, 2], [0, 1]])
B = np.array([[0, 1], [1, 0]])

print(A @ B)

[[2 1]
 [1 0]]


Usiamo `A @ x` per il prodotto tra una matrice `A` ed un vettore `x`. Il risultato è un vettore. 

In [49]:
# PRODOTTO RIGHE PER COLONNE
print(A @ x)

[27  9]


Con la funzione `np.linalg.inv(A)` possiamo invertire una matrice quadrata `A` (non singolare). Questo ci permette per esempio di risolvere numericamente sistemi lineari. Si supponga di voler risolvere $A x = b$ quando

$$
A = \left[ \begin{array}{ccc} 1 & 3 & 4 \\ 9 & 1 & 2 \\ 5 & 6 & 1 \end{array} \right], \qquad
b = \left[ \begin{array}{c} 13 \\ 15 \\ 8 \end{array} \right]
$$

Considerando che la matrice $A$ è invertibile, la soluzione $x=[1, 0, 3]^\top$ può essere trovata come $x=A^{-1} b$: 

In [50]:
A = np.array([[1, 3, 4], [9, 1, 2], [5, 6, 1]])
b = np.array([13, 15, 8])
x = np.linalg.inv(A) @ b
print(x)

[1. 0. 3.]


(Si veda anche il metodo `np.linalg.solve(A, b)` nella documentazione NumPy.) 

In [51]:
# metodo che risolve il sistema lineare
sol = np.linalg.solve(A,b)
sol

array([ 1.00000000e+00, -3.17206578e-17,  3.00000000e+00])

## Altre funzionalità utili
Sugli ndarray possono essere invocati metodi che calcolano quantità aggregate, quali somma (`.sum()`) e media (`.mean()`).

In [52]:
#operazioni sugli elementi della matrice
arr = np.array([[1, 2], [3, 4]])
print(arr)
print("somma elementi")
print(arr.sum()) # somma degli elementi
print("media elementi")
print(arr.mean()) # media degli elementi
print("somma elementi per riga")
print(arr.sum(axis = 1)) # somma riga per riga (aggrega le colonne)
print("somma elementi per colonna")
print(arr.sum(axis = 0)) # somma colonna per colonna (aggrega le righe)

[[1 2]
 [3 4]]
somma elementi
10
media elementi
2.5
somma elementi per riga
[3 7]
somma elementi per colonna
[4 6]


Possiamo scrivere e/o leggere i dati di un array da un file di testo tramite le funzioni `np.savetxt` e `np.loadtxt`. Ad esempio: 

In [53]:
x = np.array([[10, 20], [30, 40]])
np.savetxt('data/numpy1.txt', x, delimiter=',') # NB.: presuppone che esista una sottodirectory di nome 'data'
y = np.loadtxt('data/numpy1.txt', delimiter=',')
print(y)

[[10. 20.]
 [30. 40.]]


## Esercizio 1: Creare un dataset lineare

**Senza utilizzare alcun ciclo** `for`, create un semplice dataset consistente di un'unica variabile di input (feature) e di una variabile di output (etichetta), come segue: 

1. Assegnate la sequenza degli interi da 6 a 20 (inclusi) ad un array NumPy di nome `feature`.
2. Assegnate 15 valori ad un array NumPy di nome `label` tale che:

```
   label = (3)(feature) + 4
```
Per esempio, il primo valore di `label` dovrà essere: 

```
  label = (3)(6) + 4 = 22
 ```

In [54]:
# scrivere il proprio codice in questa cella
feature = np.arange(6,21)
label = 3*feature +4
print(f"feature: {feature}")
print(f"label: {label}")



feature: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
label: [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


Fare doppio-clic **qui** per una possibile soluzione all'Esercizio 1. 
<!--
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)
-->

## Esercizio 2: Aggiungere rumore al dataset

Per rendere il vostro dataset più realistico, aggiungete un segnale di rumore su ogni elemento dell'array `label` appena creato. Più precisamente, modificate ciascun valore presente in `label` sommandovi un valore casuale (distinto) compreso tra -2 e +2. 

**Non utilizzate cicli `for`**. Create un array `noise` con la stessa dimensione di `label` e poi sommatelo a `label`. 

In [55]:
# scrivere il proprio codice in questa cella
feature = np.arange(6,21)

label = label + np.random.random([15])
print(f"feature: {feature}")
print(f"label: {label}")

feature: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
label: [22.07713588 25.15673308 28.79351825 31.70621579 34.61701579 37.62017909
 40.9658462  43.77249194 46.42425595 49.8897012  52.77165461 55.20937293
 58.3927267  61.65749299 64.82328558]


Fare doppio-clic **qui** per una possibile soluzione all'Esercizio 2.
<!--
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)
-->

In [56]:
noise = (np.random.random([15]))
print(noise)
# 15 numeri random tra 0 e 1

[0.77591882 0.8418517  0.21210293 0.73717215 0.04384084 0.131239
 0.86387068 0.62124952 0.12474664 0.33673325 0.39328479 0.86457832
 0.98462322 0.07576928 0.14422626]


In [57]:
noise = noise *4
noise
# numeri random tra 0 e 4

array([3.10367526, 3.36740681, 0.84841172, 2.94868862, 0.17536335,
       0.524956  , 3.45548273, 2.48499809, 0.49898657, 1.34693299,
       1.57313916, 3.45831328, 3.93849288, 0.30307713, 0.57690503])

In [58]:
noise = noise -2 
noise
# numeri random tra -2 e 2

array([ 1.10367526,  1.36740681, -1.15158828,  0.94868862, -1.82463665,
       -1.475044  ,  1.45548273,  0.48499809, -1.50101343, -0.65306701,
       -0.42686084,  1.45831328,  1.93849288, -1.69692287, -1.42309497])